import os
import json
import requests
import markdown
from mcp.server.fastmcp import FastMCP
from requests.auth import HTTPBasicAuth

# ==============================================================================
# Configuration & Credentials
# ==============================================================================
ATLASSIAN_DOMAIN = os.getenv("ATLASSIAN_DOMAIN", "your-domain.atlassian.net")
ATLASSIAN_EMAIL = os.getenv("ATLASSIAN_EMAIL", "agent@yourdomain.com")
ATLASSIAN_API_TOKEN = os.getenv("ATLASSIAN_API_TOKEN", "your_api_token")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY", "AGILE")

JIRA_BASE_URL = f"https://{ATLASSIAN_DOMAIN}/rest/api/3"
CONFLUENCE_BASE_URL = f"https://{ATLASSIAN_DOMAIN}/wiki/rest/api"

# Dynamically resolve the script's directory so stdio execution finds the correct path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
WIKI_DIR = os.path.join(BASE_DIR, "wiki")
STATE_FILE = os.path.join(WIKI_DIR, "project_state.json")
SYNTHESIS_FILE = os.path.join(WIKI_DIR, "DAILY_SYNTHESIS.md")

auth = HTTPBasicAuth(ATLASSIAN_EMAIL, ATLASSIAN_API_TOKEN)
headers = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

# Initialize the FastMCP Server for Atlassian
mcp = FastMCP("AtlassianIngress")

# ==============================================================================
# MCP RESOURCES (Read-Only Context)
# ==============================================================================

@mcp.resource("atlassian://jira/active-sprint")
def get_active_sprint_issues() -> str:
    """Fetches all incomplete issues from the current Jira project."""
    jql = f"project = {JIRA_PROJECT_KEY} AND statusCategory != Done"
    url = f"{JIRA_BASE_URL}/search"
    
    try:
        response = requests.get(url, headers=headers, auth=auth, params={"jql": jql, "maxResults": 50})
        response.raise_for_status()
        issues = response.json().get("issues", [])
        
        simplified_issues = [
            {
                "key": issue["key"],
                "summary": issue["fields"]["summary"],
                "status": issue["fields"]["status"]["name"]
            } for issue in issues
        ]
        return json.dumps(simplified_issues, indent=2)
    except Exception as e:
        return json.dumps({"error": f"Failed to fetch Jira sprint: {str(e)}"})

# ==============================================================================
# MCP TOOLS (Agentic Actions)
# ==============================================================================

@mcp.tool()
def sync_local_tasks_to_jira() -> str:
    """
    Reads project_state.json and creates Jira tickets 
    for newly identified active tasks that don't have a Jira ticket yet.
    """
    if not os.path.exists(STATE_FILE):
        return f"Error: {STATE_FILE} not found."
        
    try:
        with open(STATE_FILE, "r") as f:
            state = json.load(f)
    except json.JSONDecodeError:
        return "Error: project_state.json is malformed."
        
    created_tickets = []
    tasks = state.get("tasks", {})
    
    for slug, task in tasks.items():
        # Only push tasks that are active and don't already have an external tracker ID
        if task.get("status") == "active" and "jira_key" not in task:
            payload = json.dumps({
                "fields": {
                    "project": {"key": JIRA_PROJECT_KEY},
                    "summary": f"[{slug}] {task.get('content', 'Autogenerated Task')[:200]}",
                    "description": {
                        "type": "doc",
                        "version": 1,
                        "content": [{
                            "type": "paragraph",
                            "content": [{"text": f"Source: {task.get('last_source', 'Unknown')}\nConfidence: {task.get('confidence', 0)}", "type": "text"}]
                        }]
                    },
                    "issuetype": {"name": "Task"}
                }
            })
            
            try:
                response = requests.post(f"{JIRA_BASE_URL}/issue", data=payload, headers=headers, auth=auth)
                response.raise_for_status()  # Catch 400 Bad Request issues (like bad ADF format) immediately
                
                issue_key = response.json().get("key")
                task["jira_key"] = issue_key  # Update local state dictionary
                created_tickets.append(issue_key)
            except Exception as e:
                # Log to the MCP client without crashing the entire tool execution loop
                print(f"Failed to create ticket for {slug}. API Response: {e}")
                
    # Save the updated state with the new Jira Keys
    if created_tickets:
        try:
            with open(STATE_FILE, "w") as f:
                json.dump(state, f, indent=4)
        except Exception as e:
            return f"Created {len(created_tickets)} tickets, but failed to save state back to disk: {e}"
            
    return f"Successfully created {len(created_tickets)} Jira tickets: {', '.join(created_tickets)}" if created_tickets else "No new active tasks required Jira synchronization."

@mcp.tool()
def publish_synthesis_to_confluence(page_id: str) -> str:
    """
    Reads the DAILY_SYNTHESIS.md, dynamically converts it to strict XHTML, 
    and publishes it to a specific Confluence page.
    """
    if not os.path.exists(SYNTHESIS_FILE):
        return f"Error: {SYNTHESIS_FILE} not found. Has the main pipeline run?"
        
    with open(SYNTHESIS_FILE, "r") as f:
        raw_markdown = f.read()
        
    # Convert Markdown to the strict XHTML expected by Confluence Storage Format.
    # Extensions ensure that tables, code blocks, and list indentations render correctly.
    try:
        xhtml_content = markdown.markdown(
            raw_markdown,
            extensions=['tables', 'fenced_code', 'sane_lists'],
            output_format="xhtml"
        )
    except Exception as e:
        return f"Error converting Markdown to XHTML: {str(e)}"
    
    try:
        # Get current page version to increment it safely
        get_resp = requests.get(f"{CONFLUENCE_BASE_URL}/content/{page_id}", headers=headers, auth=auth)
        get_resp.raise_for_status()
        
        page_data = get_resp.json()
        current_version = page_data["version"]["number"]
        page_title = page_data["title"]
        
        payload = json.dumps({
            "version": {"number": current_version + 1},
            "title": page_title,
            "type": "page",
            "body": {
                "storage": {
                    "value": xhtml_content,
                    "representation": "storage"
                }
            }
        })
        
        put_resp = requests.put(f"{CONFLUENCE_BASE_URL}/content/{page_id}", data=payload, headers=headers, auth=auth)
        put_resp.raise_for_status()
        
        return f"Successfully updated Confluence page '{page_title}' (ID: {page_id}) to version {current_version + 1}."
    except Exception as e:
        return f"Failed to publish to Confluence: {str(e)}"

# ==============================================================================
# Execution
# ==============================================================================
if __name__ == "__main__":
    print("Starting Atlassian Ingress MCP Server...")
    mcp.run(transport="stdio")
